// kits/Inertia/Teams/Svelte/resources/js/components/CancelInvitationModal.svelte
<script lang="ts">
    import { router } from '@inertiajs/svelte';
    import { Button } from '@/components/ui/button';
    import {
        Dialog,
        DialogClose,
        DialogContent,
        DialogDescription,
        DialogFooter,
        DialogTitle,
    } from '@/components/ui/dialog';
    import type { Team, TeamInvitation } from '@/types';
    import { destroy as destroyInvitation } from '@/routes/teams/invitations';

    let {
        team,
        invitation,
        open = $bindable(),
    }: {
        team: Team;
        invitation: TeamInvitation | null;
        open: boolean;
    } = $props();

    const cancelInvitation = () => {
        if (!invitation) {
            return;
        }

        router.delete(destroyInvitation([team.slug, invitation.code]).url, {
            onSuccess: () => {
                open = false;
            },
        });
    };
</script>

<Dialog bind:open>
    <DialogContent>
        <div class="space-y-3">
            <DialogTitle>Cancel invitation</DialogTitle>
            <DialogDescription class="mb-3">
                Are you sure you want to cancel the invitation for <strong
                    >{invitation?.email}</strong
                >?
            </DialogDescription>
        </div>

        <DialogFooter class="gap-2">
            <DialogClose>
                <Button variant="secondary">Keep Invitation</Button>
            </DialogClose>

            <Button variant="destructive" onclick={cancelInvitation}
                >Cancel Invitation</Button
            >
        </DialogFooter>
    </DialogContent>
</Dialog>

// kits/Inertia/Teams/React/resources/js/components/cancel-invitation-modal.tsx
import { router } from '@inertiajs/react';
import { Button } from '@/components/ui/button';
import {
    Dialog,
    DialogClose,
    DialogContent,
    DialogDescription,
    DialogFooter,
    DialogHeader,
    DialogTitle,
} from '@/components/ui/dialog';
import type { Team, TeamInvitation } from '@/types';
import { destroy as destroyInvitation } from '@/routes/teams/invitations';

type Props = {
    team: Team;
    invitation: TeamInvitation | null;
    open: boolean;
    onOpenChange: (open: boolean) => void;
};

export default function CancelInvitationModal({
    team,
    invitation,
    open,
    onOpenChange,
}: Props) {
    const cancelInvitation = () => {
        if (!invitation) {
            return;
        }

        router.delete(destroyInvitation([team.slug, invitation.code]).url, {
            onSuccess: () => onOpenChange(false),
        });
    };

    return (
        <Dialog open={open} onOpenChange={onOpenChange}>
            <DialogContent>
                <DialogHeader>
                    <DialogTitle>Cancel invitation</DialogTitle>
                    <DialogDescription>
                        Are you sure you want to cancel the invitation for{' '}
                        <strong>{invitation?.email}</strong>?
                    </DialogDescription>
                </DialogHeader>

                <DialogFooter className="gap-2">
                    <DialogClose asChild>
                        <Button variant="secondary">Keep Invitation</Button>
                    </DialogClose>

                    <Button variant="destructive" onClick={cancelInvitation}>
                        Cancel Invitation
                    </Button>
                </DialogFooter>
            </DialogContent>
        </Dialog>
    );
}
