// kits/Inertia/Teams/Svelte/resources/js/components/InviteMemberModal.svelte
<script lang="ts">
    import { Form } from '@inertiajs/svelte';
    import InputError from '@/components/InputError.svelte';
    import { Button } from '@/components/ui/button';
    import {
        Dialog,
        DialogClose,
        DialogContent,
        DialogDescription,
        DialogFooter,
        DialogTitle,
    } from '@/components/ui/dialog';
    import { Input } from '@/components/ui/input';
    import { Label } from '@/components/ui/label';
    import {
        Select,
        SelectContent,
        SelectItem,
        SelectTrigger,
    } from '@/components/ui/select';
    import { store as storeInvitation } from '@/routes/teams/invitations';
    import type { RoleOption, Team } from '@/types';

    let {
        team,
        availableRoles,
        open = $bindable(),
    }: {
        team: Team;
        availableRoles: RoleOption[];
        open: boolean;
    } = $props();

    let inviteRole = $state<RoleOption['value']>('member');
    let formKey = $state(0);

    const inviteRoleLabel = $derived(
        availableRoles.find((role) => role.value === inviteRole)?.label ??
            'Select a role',
    );

    function handleOpenChange(value: boolean) {
        open = value;

        if (!value) {
            inviteRole = 'member';
            formKey++;
        }
    }
</script>

<Dialog {open} onOpenChange={handleOpenChange}>
    <DialogContent>
        {#key formKey}
            <Form
                {...storeInvitation.form(team.slug)}
                class="space-y-6"
                onSuccess={() => (open = false)}
            >
                {#snippet children({ errors, processing })}
                    <div class="space-y-3">
                        <DialogTitle>Invite a team member</DialogTitle>
                        <DialogDescription>
                            Send an invitation to join this team.
                        </DialogDescription>
                    </div>

                    <div class="grid gap-4">
                        <div class="grid gap-2">
                            <Label for="email">Email address</Label>
                            <Input
                                id="email"
                                name="email"
                                type="email"
                                placeholder="colleague@example.com"
                                required
                            />
                            <InputError message={errors.email} />
                        </div>

                        <div class="grid gap-2">
                            <Label for="role">Role</Label>
                            <Select bind:value={inviteRole}>
                                <SelectTrigger class="w-full">
                                    {inviteRoleLabel}
                                </SelectTrigger>
                                <SelectContent>
                                    {#each availableRoles as role (role.value)}
                                        <SelectItem
                                            value={role.value}
                                            label={role.label}
                                        >
                                            {role.label}
                                        </SelectItem>
                                    {/each}
                                </SelectContent>
                            </Select>

                            <input
                                type="hidden"
                                name="role"
                                value={inviteRole}
                            />
                            <InputError message={errors.role} />
                        </div>
                    </div>

                    <DialogFooter class="gap-2">
                        <DialogClose>
                            <Button variant="secondary">Cancel</Button>
                        </DialogClose>

                        <Button type="submit" disabled={processing}
                            >Send invitation</Button
                        >
                    </DialogFooter>
                {/snippet}
            </Form>
        {/key}
    </DialogContent>
</Dialog>

// kits/Inertia/Teams/React/resources/js/components/invite-member-modal.tsx
import { Form } from '@inertiajs/react';
import { useState } from 'react';
import InputError from '@/components/input-error';
import { Button } from '@/components/ui/button';
import {
    Dialog,
    DialogClose,
    DialogContent,
    DialogDescription,
    DialogFooter,
    DialogHeader,
    DialogTitle,
} from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import {
    Select,
    SelectContent,
    SelectItem,
    SelectTrigger,
    SelectValue,
} from '@/components/ui/select';
import { store as storeInvitation } from '@/routes/teams/invitations';
import type { RoleOption, Team } from '@/types';

type Props = {
    team: Team;
    availableRoles: RoleOption[];
    open: boolean;
    onOpenChange: (open: boolean) => void;
};

export default function InviteMemberModal({
    team,
    availableRoles,
    open,
    onOpenChange,
}: Props) {
    const [inviteRole, setInviteRole] = useState<RoleOption['value']>('member');

    return (
        <Dialog open={open} onOpenChange={onOpenChange}>
            <DialogContent>
                <Form
                    {...storeInvitation.form(team.slug)}
                    className="space-y-6"
                    onSuccess={() => onOpenChange(false)}
                >
                    {({ errors, processing }) => (
                        <>
                            <DialogHeader>
                                <DialogTitle>Invite a team member</DialogTitle>
                                <DialogDescription>
                                    Send an invitation to join this team.
                                </DialogDescription>
                            </DialogHeader>

                            <div className="grid gap-4">
                                <div className="grid gap-2">
                                    <Label htmlFor="email">Email Address</Label>
                                    <Input
                                        id="email"
                                        name="email"
                                        type="email"
                                        placeholder="colleague@example.com"
                                        required
                                    />
                                    <InputError message={errors.email} />
                                </div>

                                <div className="grid gap-2">
                                    <Label htmlFor="role">Role</Label>
                                    <Select
                                        name="role"
                                        value={inviteRole}
                                        onValueChange={(value) =>
                                            setInviteRole(
                                                value as RoleOption['value'],
                                            )
                                        }
                                    >
                                        <SelectTrigger className="w-full">
                                            <SelectValue placeholder="Select a role" />
                                        </SelectTrigger>
                                        <SelectContent>
                                            {availableRoles.map((role) => (
                                                <SelectItem
                                                    key={role.value}
                                                    value={role.value}
                                                >
                                                    {role.label}
                                                </SelectItem>
                                            ))}
                                        </SelectContent>
                                    </Select>
                                    <InputError message={errors.role} />
                                </div>
                            </div>

                            <DialogFooter className="gap-2">
                                <DialogClose asChild>
                                    <Button variant="secondary">Cancel</Button>
                                </DialogClose>

                                <Button type="submit" disabled={processing}>
                                    Send Invitation
                                </Button>
                            </DialogFooter>
                        </>
                    )}
                </Form>
            </DialogContent>
        </Dialog>
    );
}
