// kits/Inertia/Fortify/React/resources/js/layouts/auth-layout.tsx
import { useLayoutProps } from '@inertiajs/react';
import AuthLayoutTemplate from '@/layouts/auth/auth-simple-layout';

export default function AuthLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const { title, description } = useLayoutProps({
        title: '',
        description: '',
    });

    return (
        <AuthLayoutTemplate title={title} description={description}>
            {children}
        </AuthLayoutTemplate>
    );
}

// kits/Inertia/Fortify/Svelte/resources/js/layouts/AuthLayout.svelte
<script lang="ts">
    import { useLayoutProps } from '@inertiajs/svelte';
    import type { Snippet } from 'svelte';
    import AuthLayout from '@/layouts/auth/AuthSimpleLayout.svelte';

    let {
        children,
    }: {
        children?: Snippet;
    } = $props();

    const layout = useLayoutProps({
        title: '',
        description: '',
    });
</script>

<AuthLayout title={layout.title} description={layout.description}>
    {@render children?.()}
</AuthLayout>
