// kits/Inertia/Teams/Vue/resources/js/pages/teams/Edit.vue
<script setup lang="ts">
import { Form, Head, router } from '@inertiajs/vue3';
import { ChevronDown, Mail, UserPlus, X } from 'lucide-vue-next';
import { computed, ref } from 'vue';
import CancelInvitationModal from '@/components/CancelInvitationModal.vue';
import DeleteTeamModal from '@/components/DeleteTeamModal.vue';
import Heading from '@/components/Heading.vue';
import InputError from '@/components/InputError.vue';
import InviteMemberModal from '@/components/InviteMemberModal.vue';
import RemoveMemberModal from '@/components/RemoveMemberModal.vue';
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import {
    DropdownMenu,
    DropdownMenuContent,
    DropdownMenuItem,
    DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import {
    Tooltip,
    TooltipContent,
    TooltipProvider,
    TooltipTrigger,
} from '@/components/ui/tooltip';
import { useInitials } from '@/composables/useInitials';
import AppLayout from '@/layouts/AppLayout.vue';
import SettingsLayout from '@/layouts/settings/Layout.vue';
import { edit, index, update } from '@/routes/teams';
import { update as updateMember } from '@/routes/teams/members';
import type {
    BreadcrumbItem,
    RoleOption,
    Team,
    TeamInvitation,
    TeamMember,
    TeamPermissions,
} from '@/types';

type Props = {
    team: Team;
    members: TeamMember[];
    invitations: TeamInvitation[];
    permissions: TeamPermissions;
    availableRoles: RoleOption[];
};

const props = defineProps<Props>();

const { getInitials } = useInitials();

const breadcrumbs = computed<BreadcrumbItem[]>(() => [
    {
        title: 'Teams',
        href: index().url,
    },
    {
        title: props.team.name,
        href: edit(props.team.slug).url,
    },
]);

const inviteDialogOpen = ref(false);
const deleteDialogOpen = ref(false);
const removeMemberDialogOpen = ref(false);
const memberToRemove = ref<TeamMember | null>(null);
const cancelInvitationDialogOpen = ref(false);
const invitationToCancel = ref<TeamInvitation | null>(null);

const pageTitle = computed(() =>
    props.permissions.canUpdateTeam
        ? `Edit ${props.team.name}`
        : `View ${props.team.name}`,
);

const updateMemberRole = (member: TeamMember, newRole: string) => {
    router.visit(updateMember([props.team.slug, member.id]), {
        data: { role: newRole },
        preserveScroll: true,
    });
};

const confirmRemoveMember = (member: TeamMember) => {
    memberToRemove.value = member;
    removeMemberDialogOpen.value = true;
};

const confirmCancelInvitation = (invitation: TeamInvitation) => {
    invitationToCancel.value = invitation;
    cancelInvitationDialogOpen.value = true;
};
</script>

<template>
    <AppLayout :breadcrumbs="breadcrumbs">
        <Head :title="pageTitle" />

        <h1 class="sr-only">{{ pageTitle }}</h1>

        <SettingsLayout>
            <div class="flex flex-col space-y-10">
                <!-- Team Name Section -->
                <div v-if="permissions.canUpdateTeam" class="space-y-6">
                    <Heading
                        variant="small"
                        title="Team settings"
                        description="Update your team name and settings"
                    />

                    <Form
                        v-bind="update.form(team.slug)"
                        class="space-y-6"
                        v-slot="{ errors, processing, recentlySuccessful }"
                    >
                        <div class="grid gap-2">
                            <Label for="name">Team name</Label>
                            <Input
                                id="name"
                                name="name"
                                :default-value="team.name"
                                required
                            />
                            <InputError :message="errors.name" />
                        </div>

                        <div class="flex items-center gap-4">
                            <Button type="submit" :disabled="processing">
                                Save
                            </Button>

                            <Transition
                                enter-active-class="transition ease-in-out"
                                enter-from-class="opacity-0"
                                leave-active-class="transition ease-in-out"
                                leave-to-class="opacity-0"
                            >
                                <p
                                    v-show="recentlySuccessful"
                                    class="text-sm text-neutral-600"
                                >
                                    Saved.
                                </p>
                            </Transition>
                        </div>
                    </Form>
                </div>

                <div v-else class="space-y-6">
                    <Heading variant="small" :title="team.name" />
                </div>

                <!-- Members Section -->
                <div class="space-y-6">
                    <div class="flex items-center justify-between">
                        <Heading
                            variant="small"
                            title="Team members"
                            :description="
                                permissions.canCreateInvitation
                                    ? 'Manage who belongs to this team'
                                    : ''
                            "
                        />

                        <Button
                            v-if="permissions.canCreateInvitation"
                            @click="inviteDialogOpen = true"
                        >
                            <UserPlus /> Invite member
                        </Button>
                    </div>

                    <div class="space-y-3">
                        <div
                            v-for="member in members"
                            :key="member.id"
                            class="flex items-center justify-between rounded-lg border p-4"
                        >
                            <div class="flex items-center gap-4">
                                <Avatar class="h-10 w-10">
                                    <AvatarImage
                                        v-if="member.avatar"
                                        :src="member.avatar"
                                        :alt="member.name"
                                    />
                                    <AvatarFallback>{{
                                        getInitials(member.name)
                                    }}</AvatarFallback>
                                </Avatar>
                                <div>
                                    <div class="font-medium">
                                        {{ member.name }}
                                    </div>
                                    <div class="text-sm text-muted-foreground">
                                        {{ member.email }}
                                    </div>
                                </div>
                            </div>

                            <div class="flex items-center gap-2">
                                <DropdownMenu
                                    v-if="
                                        member.role !== 'owner' &&
                                        permissions.canUpdateMember
                                    "
                                >
                                    <DropdownMenuTrigger as-child>
                                        <Button variant="outline" size="sm">
                                            {{ member.role_label }}
                                            <ChevronDown
                                                class="ml-2 h-4 w-4 opacity-50"
                                            />
                                        </Button>
                                    </DropdownMenuTrigger>
                                    <DropdownMenuContent>
                                        <DropdownMenuItem
                                            v-for="role in availableRoles"
                                            :key="role.value"
                                            @click="
                                                updateMemberRole(
                                                    member,
                                                    role.value,
                                                )
                                            "
                                        >
                                            {{ role.label }}
                                        </DropdownMenuItem>
                                    </DropdownMenuContent>
                                </DropdownMenu>
                                <Badge v-else variant="secondary">
                                    {{ member.role_label }}
                                </Badge>

                                <TooltipProvider
                                    v-if="
                                        member.role !== 'owner' &&
                                        permissions.canRemoveMember
                                    "
                                >
                                    <Tooltip>
                                        <TooltipTrigger as-child>
                                            <Button
                                                variant="ghost"
                                                size="sm"
                                                @click="
                                                    confirmRemoveMember(member)
                                                "
                                            >
                                                <X class="h-4 w-4" />
                                            </Button>
                                        </TooltipTrigger>
                                        <TooltipContent>
                                            <p>Remove member</p>
                                        </TooltipContent>
                                    </Tooltip>
                                </TooltipProvider>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Pending Invitations Section -->
                <div v-if="invitations.length > 0" class="space-y-6">
                    <Heading
                        variant="small"
                        title="Pending invitations"
                        description="Invitations that haven't been accepted yet"
                    />

                    <div class="space-y-3">
                        <div
                            v-for="invitation in invitations"
                            :key="invitation.code"
                            class="flex items-center justify-between rounded-lg border p-4"
                        >
                            <div class="flex items-center gap-4">
                                <div
                                    class="flex h-10 w-10 items-center justify-center rounded-full bg-muted"
                                >
                                    <Mail
                                        class="h-5 w-5 text-muted-foreground"
                                    />
                                </div>
                                <div>
                                    <div class="font-medium">
                                        {{ invitation.email }}
                                    </div>
                                    <div class="text-sm text-muted-foreground">
                                        {{ invitation.role_label }}
                                    </div>
                                </div>
                            </div>

                            <TooltipProvider
                                v-if="permissions.canCancelInvitation"
                            >
                                <Tooltip>
                                    <TooltipTrigger as-child>
                                        <Button
                                            variant="ghost"
                                            size="sm"
                                            @click="
                                                confirmCancelInvitation(
                                                    invitation,
                                                )
                                            "
                                        >
                                            <X class="h-4 w-4" />
                                        </Button>
                                    </TooltipTrigger>
                                    <TooltipContent>
                                        <p>Cancel invitation</p>
                                    </TooltipContent>
                                </Tooltip>
                            </TooltipProvider>
                        </div>
                    </div>
                </div>

                <!-- Danger Zone -->
                <div
                    v-if="permissions.canDeleteTeam && !team.isPersonal"
                    class="space-y-6"
                >
                    <Heading
                        variant="small"
                        title="Delete team"
                        description="Permanently delete your team"
                    />
                    <div
                        class="space-y-4 rounded-lg border border-red-100 bg-red-50 p-4 dark:border-red-200/10 dark:bg-red-700/10"
                    >
                        <div
                            class="relative space-y-0.5 text-red-600 dark:text-red-100"
                        >
                            <p class="font-medium">Warning</p>
                            <p class="text-sm">
                                Please proceed with caution, this cannot be
                                undone.
                            </p>
                        </div>
                        <Button
                            variant="destructive"
                            @click="deleteDialogOpen = true"
                            >Delete team</Button
                        >
                    </div>
                </div>
            </div>

            <InviteMemberModal
                v-if="permissions.canCreateInvitation"
                :team="team"
                :available-roles="availableRoles"
                :open="inviteDialogOpen"
                @update:open="inviteDialogOpen = $event"
            />

            <RemoveMemberModal
                :team="team"
                :member="memberToRemove"
                :open="removeMemberDialogOpen"
                @update:open="removeMemberDialogOpen = $event"
            />

            <CancelInvitationModal
                :team="team"
                :invitation="invitationToCancel"
                :open="cancelInvitationDialogOpen"
                @update:open="cancelInvitationDialogOpen = $event"
            />

            <DeleteTeamModal
                v-if="permissions.canDeleteTeam && !team.isPersonal"
                :team="team"
                :open="deleteDialogOpen"
                @update:open="deleteDialogOpen = $event"
            />
        </SettingsLayout>
    </AppLayout>
</template>

// kits/Inertia/Teams/React/resources/js/pages/teams/edit.tsx
import { Transition } from '@headlessui/react';
import { Form, Head, router } from '@inertiajs/react';
import { ChevronDown, Mail, UserPlus, X } from 'lucide-react';
import { useMemo, useState } from 'react';
import CancelInvitationModal from '@/components/cancel-invitation-modal';
import DeleteTeamModal from '@/components/delete-team-modal';
import Heading from '@/components/heading';
import InputError from '@/components/input-error';
import InviteMemberModal from '@/components/invite-member-modal';
import RemoveMemberModal from '@/components/remove-member-modal';
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import {
    DropdownMenu,
    DropdownMenuContent,
    DropdownMenuItem,
    DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import {
    Tooltip,
    TooltipContent,
    TooltipProvider,
    TooltipTrigger,
} from '@/components/ui/tooltip';
import { useInitials } from '@/hooks/use-initials';
import AppLayout from '@/layouts/app-layout';
import SettingsLayout from '@/layouts/settings/layout';
import { edit, index, update } from '@/routes/teams';
import { update as updateMember } from '@/routes/teams/members';
import type {
    BreadcrumbItem,
    RoleOption,
    Team,
    TeamInvitation,
    TeamMember,
    TeamPermissions,
} from '@/types';

type Props = {
    team: Team;
    members: TeamMember[];
    invitations: TeamInvitation[];
    permissions: TeamPermissions;
    availableRoles: RoleOption[];
};

export default function TeamEdit({
    team,
    members,
    invitations,
    permissions,
    availableRoles,
}: Props) {
    const getInitials = useInitials();
    const breadcrumbs = useMemo<BreadcrumbItem[]>(
        () => [
            {
                title: 'Teams',
                href: index().url,
            },
            {
                title: team.name,
                href: edit(team.slug).url,
            },
        ],
        [team.name, team.slug],
    );

    const [inviteDialogOpen, setInviteDialogOpen] = useState(false);
    const [deleteDialogOpen, setDeleteDialogOpen] = useState(false);
    const [removeMemberDialogOpen, setRemoveMemberDialogOpen] = useState(false);
    const [memberToRemove, setMemberToRemove] = useState<TeamMember | null>(
        null,
    );
    const [cancelInvitationDialogOpen, setCancelInvitationDialogOpen] =
        useState(false);
    const [invitationToCancel, setInvitationToCancel] =
        useState<TeamInvitation | null>(null);

    const pageTitle = useMemo(
        () =>
            permissions.canUpdateTeam
                ? `Edit ${team.name}`
                : `View ${team.name}`,
        [permissions.canUpdateTeam, team.name],
    );

    const updateMemberRole = (member: TeamMember, newRole: string) => {
        router.visit(updateMember([team.slug, member.id]), {
            data: { role: newRole },
            preserveScroll: true,
        });
    };

    const confirmRemoveMember = (member: TeamMember) => {
        setMemberToRemove(member);
        setRemoveMemberDialogOpen(true);
    };

    const confirmCancelInvitation = (invitation: TeamInvitation) => {
        setInvitationToCancel(invitation);
        setCancelInvitationDialogOpen(true);
    };

    return (
        <AppLayout breadcrumbs={breadcrumbs}>
            <Head title={pageTitle} />

            <h1 className="sr-only">{pageTitle}</h1>

            <SettingsLayout>
                <div className="flex flex-col space-y-10">
                    <div className="space-y-6">
                        {permissions.canUpdateTeam ? (
                            <>
                                <Heading
                                    variant="small"
                                    title="Team settings"
                                    description="Update your team name and settings"
                                />

                                <Form
                                    {...update.form(team.slug)}
                                    className="space-y-6"
                                >
                                    {({
                                        errors,
                                        processing,
                                        recentlySuccessful,
                                    }) => (
                                        <>
                                            <div className="grid gap-2">
                                                <Label htmlFor="name">
                                                    Team name
                                                </Label>
                                                <Input
                                                    id="name"
                                                    name="name"
                                                    defaultValue={team.name}
                                                    required
                                                />
                                                <InputError
                                                    message={errors.name}
                                                />
                                            </div>

                                            <div className="flex items-center gap-4">
                                                <Button
                                                    type="submit"
                                                    disabled={processing}
                                                >
                                                    Save
                                                </Button>

                                                <Transition
                                                    show={recentlySuccessful}
                                                    enter="transition ease-in-out"
                                                    enterFrom="opacity-0"
                                                    leave="transition ease-in-out"
                                                    leaveTo="opacity-0"
                                                >
                                                    <p className="text-sm text-neutral-600">
                                                        Saved.
                                                    </p>
                                                </Transition>
                                            </div>
                                        </>
                                    )}
                                </Form>
                            </>
                        ) : (
                            <>
                                <Heading variant="small" title={team.name} />
                            </>
                        )}
                    </div>

                    <div className="space-y-6">
                        <div className="flex items-center justify-between">
                            <Heading
                                variant="small"
                                title="Team members"
                                description={
                                    permissions.canCreateInvitation
                                        ? 'Manage who belongs to this team'
                                        : ''
                                }
                            />

                            {permissions.canCreateInvitation ? (
                                <Button
                                    onClick={() => setInviteDialogOpen(true)}
                                >
                                    <UserPlus /> Invite member
                                </Button>
                            ) : null}
                        </div>

                        <div className="space-y-3">
                            {members.map((member) => (
                                <div
                                    key={member.id}
                                    className="flex items-center justify-between rounded-lg border p-4"
                                >
                                    <div className="flex items-center gap-4">
                                        <Avatar className="h-10 w-10">
                                            {member.avatar ? (
                                                <AvatarImage
                                                    src={member.avatar}
                                                    alt={member.name}
                                                />
                                            ) : null}
                                            <AvatarFallback>
                                                {getInitials(member.name)}
                                            </AvatarFallback>
                                        </Avatar>
                                        <div>
                                            <div className="font-medium">
                                                {member.name}
                                            </div>
                                            <div className="text-sm text-muted-foreground">
                                                {member.email}
                                            </div>
                                        </div>
                                    </div>

                                    <div className="flex items-center gap-2">
                                        {member.role !== 'owner' &&
                                        permissions.canUpdateMember ? (
                                            <DropdownMenu>
                                                <DropdownMenuTrigger asChild>
                                                    <Button
                                                        variant="outline"
                                                        size="sm"
                                                    >
                                                        {member.role_label}
                                                        <ChevronDown className="ml-2 h-4 w-4 opacity-50" />
                                                    </Button>
                                                </DropdownMenuTrigger>
                                                <DropdownMenuContent>
                                                    {availableRoles.map(
                                                        (role) => (
                                                            <DropdownMenuItem
                                                                key={role.value}
                                                                onSelect={() =>
                                                                    updateMemberRole(
                                                                        member,
                                                                        role.value,
                                                                    )
                                                                }
                                                            >
                                                                {role.label}
                                                            </DropdownMenuItem>
                                                        ),
                                                    )}
                                                </DropdownMenuContent>
                                            </DropdownMenu>
                                        ) : (
                                            <Badge variant="secondary">
                                                {member.role_label}
                                            </Badge>
                                        )}

                                        {member.role !== 'owner' &&
                                        permissions.canRemoveMember ? (
                                            <TooltipProvider>
                                                <Tooltip>
                                                    <TooltipTrigger asChild>
                                                        <Button
                                                            variant="ghost"
                                                            size="sm"
                                                            onClick={() =>
                                                                confirmRemoveMember(
                                                                    member,
                                                                )
                                                            }
                                                        >
                                                            <X className="h-4 w-4" />
                                                        </Button>
                                                    </TooltipTrigger>
                                                    <TooltipContent>
                                                        <p>Remove member</p>
                                                    </TooltipContent>
                                                </Tooltip>
                                            </TooltipProvider>
                                        ) : null}
                                    </div>
                                </div>
                            ))}
                        </div>
                    </div>

                    {invitations.length > 0 ? (
                        <div className="space-y-6">
                            <Heading
                                variant="small"
                                title="Pending invitations"
                                description="Invitations that haven't been accepted yet"
                            />

                            <div className="space-y-3">
                                {invitations.map((invitation) => (
                                    <div
                                        key={invitation.code}
                                        className="flex items-center justify-between rounded-lg border p-4"
                                    >
                                        <div className="flex items-center gap-4">
                                            <div className="flex h-10 w-10 items-center justify-center rounded-full bg-muted">
                                                <Mail className="h-5 w-5 text-muted-foreground" />
                                            </div>
                                            <div>
                                                <div className="font-medium">
                                                    {invitation.email}
                                                </div>
                                                <div className="text-sm text-muted-foreground">
                                                    {invitation.role_label}
                                                </div>
                                            </div>
                                        </div>

                                        {permissions.canCancelInvitation ? (
                                            <TooltipProvider>
                                                <Tooltip>
                                                    <TooltipTrigger asChild>
                                                        <Button
                                                            variant="ghost"
                                                            size="sm"
                                                            onClick={() =>
                                                                confirmCancelInvitation(
                                                                    invitation,
                                                                )
                                                            }
                                                        >
                                                            <X className="h-4 w-4" />
                                                        </Button>
                                                    </TooltipTrigger>
                                                    <TooltipContent>
                                                        <p>Cancel invitation</p>
                                                    </TooltipContent>
                                                </Tooltip>
                                            </TooltipProvider>
                                        ) : null}
                                    </div>
                                ))}
                            </div>
                        </div>
                    ) : null}

                    {permissions.canDeleteTeam && !team.isPersonal ? (
                        <div className="space-y-6">
                            <Heading
                                variant="small"
                                title="Delete team"
                                description="Permanently delete your team"
                            />
                            <div className="space-y-4 rounded-lg border border-red-100 bg-red-50 p-4 dark:border-red-200/10 dark:bg-red-700/10">
                                <div className="relative space-y-0.5 text-red-600 dark:text-red-100">
                                    <p className="font-medium">Warning</p>
                                    <p className="text-sm">
                                        Please proceed with caution, this cannot
                                        be undone.
                                    </p>
                                </div>
                                <Button
                                    variant="destructive"
                                    onClick={() => setDeleteDialogOpen(true)}
                                >
                                    Delete team
                                </Button>
                            </div>
                        </div>
                    ) : null}
                </div>

                {permissions.canCreateInvitation ? (
                    <InviteMemberModal
                        team={team}
                        availableRoles={availableRoles}
                        open={inviteDialogOpen}
                        onOpenChange={setInviteDialogOpen}
                    />
                ) : null}

                <RemoveMemberModal
                    team={team}
                    member={memberToRemove}
                    open={removeMemberDialogOpen}
                    onOpenChange={setRemoveMemberDialogOpen}
                />

                <CancelInvitationModal
                    team={team}
                    invitation={invitationToCancel}
                    open={cancelInvitationDialogOpen}
                    onOpenChange={setCancelInvitationDialogOpen}
                />

                {permissions.canDeleteTeam && !team.isPersonal ? (
                    <DeleteTeamModal
                        team={team}
                        open={deleteDialogOpen}
                        onOpenChange={setDeleteDialogOpen}
                    />
                ) : null}
            </SettingsLayout>
        </AppLayout>
    );
}
