// kits/Inertia/Teams/Vue/resources/js/pages/teams/Index.vue
<script setup lang="ts">
import { Head, Link, router } from '@inertiajs/vue3';
import { CheckCircle, Circle, Eye, Pencil, Plus } from 'lucide-vue-next';
import CreateTeamModal from '@/components/CreateTeamModal.vue';
import Heading from '@/components/Heading.vue';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import {
    Tooltip,
    TooltipContent,
    TooltipProvider,
    TooltipTrigger,
} from '@/components/ui/tooltip';
import AppLayout from '@/layouts/AppLayout.vue';
import SettingsLayout from '@/layouts/settings/Layout.vue';
import { edit, index, switchMethod } from '@/routes/teams';
import type { BreadcrumbItem, Team } from '@/types';

type Props = {
    teams: Team[];
};

defineProps<Props>();

const breadcrumbs: BreadcrumbItem[] = [
    {
        title: 'Teams',
        href: index().url,
    },
];

const switchTeam = (team: Team) => router.post(switchMethod(team.slug).url);
</script>

<template>
    <AppLayout :breadcrumbs="breadcrumbs">
        <Head title="Teams" />

        <h1 class="sr-only">Teams</h1>

        <SettingsLayout>
            <div class="flex flex-col space-y-6">
                <div class="flex items-center justify-between">
                    <Heading
                        variant="small"
                        title="Teams"
                        description="Manage your teams and team memberships"
                    />

                    <CreateTeamModal>
                        <Button> <Plus /> Create Team </Button>
                    </CreateTeamModal>
                </div>

                <div class="space-y-3">
                    <div
                        v-for="team in teams"
                        :key="team.id"
                        class="flex items-center justify-between rounded-lg border p-4"
                        :class="{
                            'border-ring/60': team.isCurrent,
                        }"
                    >
                        <div class="flex items-center gap-4">
                            <div>
                                <div class="flex items-center gap-2">
                                    <span class="font-medium">{{
                                        team.name
                                    }}</span>
                                    <Badge
                                        v-if="team.isPersonal"
                                        variant="secondary"
                                    >
                                        Personal
                                    </Badge>
                                </div>
                                <span class="text-sm text-muted-foreground">
                                    {{ team.roleLabel }}
                                </span>
                            </div>
                        </div>

                        <TooltipProvider>
                            <div class="flex items-center gap-2">
                                <Tooltip v-if="team.isCurrent">
                                    <TooltipTrigger as-child>
                                        <Button variant="ghost" size="sm">
                                            <CheckCircle class="h-4 w-4" />
                                        </Button>
                                    </TooltipTrigger>
                                    <TooltipContent>
                                        <p>Current team</p>
                                    </TooltipContent>
                                </Tooltip>

                                <Tooltip v-if="!team.isCurrent">
                                    <TooltipTrigger as-child>
                                        <Button
                                            variant="ghost"
                                            size="sm"
                                            @click="switchTeam(team)"
                                        >
                                            <Circle
                                                class="h-4 w-4 text-muted-foreground"
                                            />
                                        </Button>
                                    </TooltipTrigger>
                                    <TooltipContent>
                                        <p>Set as current team</p>
                                    </TooltipContent>
                                </Tooltip>

                                <Tooltip v-if="team.role === 'member'">
                                    <TooltipTrigger as-child>
                                        <Button
                                            variant="ghost"
                                            size="sm"
                                            as-child
                                        >
                                            <Link :href="edit(team.slug).url">
                                                <Eye class="h-4 w-4" />
                                            </Link>
                                        </Button>
                                    </TooltipTrigger>
                                    <TooltipContent>
                                        <p>View team</p>
                                    </TooltipContent>
                                </Tooltip>

                                <Tooltip v-else>
                                    <TooltipTrigger as-child>
                                        <Button
                                            variant="ghost"
                                            size="sm"
                                            as-child
                                        >
                                            <Link :href="edit(team.slug).url">
                                                <Pencil class="h-4 w-4" />
                                            </Link>
                                        </Button>
                                    </TooltipTrigger>
                                    <TooltipContent>
                                        <p>Edit team</p>
                                    </TooltipContent>
                                </Tooltip>
                            </div>
                        </TooltipProvider>
                    </div>

                    <p
                        v-if="teams.length === 0"
                        class="py-8 text-center text-muted-foreground"
                    >
                        You don't belong to any teams yet.
                    </p>
                </div>
            </div>
        </SettingsLayout>
    </AppLayout>
</template>

// kits/Inertia/Teams/React/resources/js/pages/teams/index.tsx
import { Head, Link, router } from '@inertiajs/react';
import { CheckCircle, Circle, Eye, Pencil, Plus } from 'lucide-react';
import CreateTeamModal from '@/components/create-team-modal';
import Heading from '@/components/heading';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import {
    Tooltip,
    TooltipContent,
    TooltipProvider,
    TooltipTrigger,
} from '@/components/ui/tooltip';
import AppLayout from '@/layouts/app-layout';
import SettingsLayout from '@/layouts/settings/layout';
import type { BreadcrumbItem, Team } from '@/types';
import { edit, index, switchMethod } from '@/routes/teams';

type Props = {
    teams: Team[];
};

const breadcrumbs: BreadcrumbItem[] = [
    {
        title: 'Teams',
        href: index().url,
    },
];

const switchTeam = (team: Team) => router.post(switchMethod(team.slug).url);

export default function TeamsIndex({ teams }: Props) {
    return (
        <AppLayout breadcrumbs={breadcrumbs}>
            <Head title="Teams" />

            <h1 className="sr-only">Teams</h1>

            <SettingsLayout>
                <div className="flex flex-col space-y-6">
                    <div className="flex items-center justify-between">
                        <Heading
                            variant="small"
                            title="Teams"
                            description="Manage your teams and team memberships"
                        />

                        <CreateTeamModal>
                            <Button>
                                <Plus /> Create Team
                            </Button>
                        </CreateTeamModal>
                    </div>

                    <div className="space-y-3">
                        {teams.map((team) => (
                            <div
                                key={team.id}
                                className={`flex items-center justify-between rounded-lg border p-4 ${team.isCurrent ? 'border-ring' : ''}`}
                            >
                                <div className="flex items-center gap-4">
                                    <div>
                                        <div className="flex items-center gap-2">
                                            <span className="font-medium">
                                                {team.name}
                                            </span>
                                            {team.isPersonal ? (
                                                <Badge variant="secondary">
                                                    Personal
                                                </Badge>
                                            ) : null}
                                        </div>
                                        <span className="text-sm text-muted-foreground">
                                            {team.roleLabel}
                                        </span>
                                    </div>
                                </div>

                                <TooltipProvider>
                                    <div className="flex items-center gap-2">
                                        {team.isCurrent ? (
                                            <Tooltip>
                                                <TooltipTrigger asChild>
                                                    <Button
                                                        variant="ghost"
                                                        size="sm"
                                                    >
                                                        <CheckCircle className="h-4 w-4" />
                                                    </Button>
                                                </TooltipTrigger>
                                                <TooltipContent>
                                                    <p>Current team</p>
                                                </TooltipContent>
                                            </Tooltip>
                                        ) : (
                                            <Tooltip>
                                                <TooltipTrigger asChild>
                                                    <Button
                                                        variant="ghost"
                                                        size="sm"
                                                        onClick={() =>
                                                            switchTeam(team)
                                                        }
                                                    >
                                                        <Circle className="h-4 w-4 text-muted-foreground" />
                                                    </Button>
                                                </TooltipTrigger>
                                                <TooltipContent>
                                                    <p>Set as current team</p>
                                                </TooltipContent>
                                            </Tooltip>
                                        )}

                                        {team.role === 'member' ? (
                                            <Tooltip>
                                                <TooltipTrigger asChild>
                                                    <Button
                                                        variant="ghost"
                                                        size="sm"
                                                        asChild
                                                    >
                                                        <Link
                                                            href={
                                                                edit(team.slug)
                                                                    .url
                                                            }
                                                        >
                                                            <Eye className="h-4 w-4" />
                                                        </Link>
                                                    </Button>
                                                </TooltipTrigger>
                                                <TooltipContent>
                                                    <p>View team</p>
                                                </TooltipContent>
                                            </Tooltip>
                                        ) : (
                                            <Tooltip>
                                                <TooltipTrigger asChild>
                                                    <Button
                                                        variant="ghost"
                                                        size="sm"
                                                        asChild
                                                    >
                                                        <Link
                                                            href={
                                                                edit(team.slug)
                                                                    .url
                                                            }
                                                        >
                                                            <Pencil className="h-4 w-4" />
                                                        </Link>
                                                    </Button>
                                                </TooltipTrigger>
                                                <TooltipContent>
                                                    <p>Edit team</p>
                                                </TooltipContent>
                                            </Tooltip>
                                        )}
                                    </div>
                                </TooltipProvider>
                            </div>
                        ))}

                        {teams.length === 0 ? (
                            <p className="py-8 text-center text-muted-foreground">
                                You don't belong to any teams yet.
                            </p>
                        ) : null}
                    </div>
                </div>
            </SettingsLayout>
        </AppLayout>
    );
}
