// kits/Inertia/Fortify/Vue/resources/js/pages/settings/Security.vue
<script setup lang="ts">
import { Form, Head, router } from '@inertiajs/vue3';
import { KeyRound, ShieldBan, ShieldCheck } from 'lucide-vue-next';
import { onUnmounted, ref } from 'vue';
import { destroy } from '@/actions/Laravel/Passkeys/Http/Controllers/PasskeyRegistrationController';
import SecurityController from '@/actions/App/Http/Controllers/Settings/SecurityController';
import Heading from '@/components/Heading.vue';
import InputError from '@/components/InputError.vue';
import PasskeyItem from '@/components/PasskeyItem.vue';
import PasskeyRegister from '@/components/PasskeyRegister.vue';
import PasswordInput from '@/components/PasswordInput.vue';
import TwoFactorRecoveryCodes from '@/components/TwoFactorRecoveryCodes.vue';
import TwoFactorSetupModal from '@/components/TwoFactorSetupModal.vue';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Label } from '@/components/ui/label';
import { useTwoFactorAuth } from '@/composables/useTwoFactorAuth';
import AppLayout from '@/layouts/AppLayout.vue';
import SettingsLayout from '@/layouts/settings/Layout.vue';
import { edit } from '@/routes/security';
import { disable, enable } from '@/routes/two-factor';
import type { BreadcrumbItem } from '@/types';

type Passkey = {
    id: number;
    name: string;
    authenticator: string | null;
    created_at_diff: string;
    last_used_at_diff: string | null;
};

type Props = {
    canManageTwoFactor?: boolean;
    canManagePasskeys?: boolean;
    passkeys?: Passkey[];
    requiresConfirmation?: boolean;
    twoFactorEnabled?: boolean;
};

withDefaults(defineProps<Props>(), {
    canManageTwoFactor: false,
    canManagePasskeys: false,
    passkeys: () => [],
    requiresConfirmation: false,
    twoFactorEnabled: false,
});

const breadcrumbs: BreadcrumbItem[] = [
    {
        title: 'Security settings',
        href: edit(),
    },
];

const { hasSetupData, clearTwoFactorAuthData } = useTwoFactorAuth();
const showSetupModal = ref<boolean>(false);

const handleDelete = (id: number) => {
    router.delete(destroy.url(id), {
        preserveScroll: true,
    });
};

const handleRegisterSuccess = () => {
    router.reload({
        preserveScroll: true,
    });
};

onUnmounted(() => clearTwoFactorAuthData());
</script>

<template>
    <AppLayout :breadcrumbs="breadcrumbs">
        <Head title="Security settings" />

        <h1 class="sr-only">Security settings</h1>

        <SettingsLayout>
            <div class="space-y-6">
                <Heading
                    variant="small"
                    title="Update password"
                    description="Ensure your account is using a long, random password to stay secure"
                />

                <Form
                    v-bind="SecurityController.update.form()"
                    :options="{
                        preserveScroll: true,
                    }"
                    reset-on-success
                    :reset-on-error="[
                        'password',
                        'password_confirmation',
                        'current_password',
                    ]"
                    class="space-y-6"
                    v-slot="{ errors, processing, recentlySuccessful }"
                >
                    <div class="grid gap-2">
                        <Label for="current_password">Current password</Label>
                        <PasswordInput
                            id="current_password"
                            name="current_password"
                            class="mt-1 block w-full"
                            autocomplete="current-password"
                            placeholder="Current password"
                        />
                        <InputError :message="errors.current_password" />
                    </div>

                    <div class="grid gap-2">
                        <Label for="password">New password</Label>
                        <PasswordInput
                            id="password"
                            name="password"
                            class="mt-1 block w-full"
                            autocomplete="new-password"
                            placeholder="New password"
                        />
                        <InputError :message="errors.password" />
                    </div>

                    <div class="grid gap-2">
                        <Label for="password_confirmation"
                            >Confirm password</Label
                        >
                        <PasswordInput
                            id="password_confirmation"
                            name="password_confirmation"
                            class="mt-1 block w-full"
                            autocomplete="new-password"
                            placeholder="Confirm password"
                        />
                        <InputError :message="errors.password_confirmation" />
                    </div>

                    <div class="flex items-center gap-4">
                        <Button
                            :disabled="processing"
                            data-test="update-password-button"
                            >Save password</Button
                        >

                        <Transition
                            enter-active-class="transition ease-in-out"
                            enter-from-class="opacity-0"
                            leave-active-class="transition ease-in-out"
                            leave-to-class="opacity-0"
                        >
                            <p
                                v-show="recentlySuccessful"
                                class="text-sm text-neutral-600"
                            >
                                Saved.
                            </p>
                        </Transition>
                    </div>
                </Form>
            </div>

            <div v-if="canManageTwoFactor" class="space-y-6">
                <Heading
                    variant="small"
                    title="Two-factor authentication"
                    description="Manage your two-factor authentication settings"
                />

                <div
                    v-if="!twoFactorEnabled"
                    class="flex flex-col items-start justify-start space-y-4"
                >
                    <Badge variant="destructive">Disabled</Badge>

                    <p class="text-muted-foreground">
                        When you enable two-factor authentication, you will be
                        prompted for a secure pin during login. This pin can be
                        retrieved from a TOTP-supported application on your
                        phone.
                    </p>

                    <div>
                        <Button
                            v-if="hasSetupData"
                            @click="showSetupModal = true"
                        >
                            <ShieldCheck />Continue setup
                        </Button>
                        <Form
                            v-else
                            v-bind="enable.form()"
                            @success="showSetupModal = true"
                            #default="{ processing }"
                        >
                            <Button type="submit" :disabled="processing">
                                <ShieldCheck />Enable 2FA</Button
                            ></Form
                        >
                    </div>
                </div>

                <div
                    v-else
                    class="flex flex-col items-start justify-start space-y-4"
                >
                    <Badge variant="default">Enabled</Badge>

                    <p class="text-muted-foreground">
                        With two-factor authentication enabled, you will be
                        prompted for a secure, random pin during login, which
                        you can retrieve from the TOTP-supported application on
                        your phone.
                    </p>

                    <TwoFactorRecoveryCodes />

                    <div class="relative inline">
                        <Form v-bind="disable.form()" #default="{ processing }">
                            <Button
                                variant="destructive"
                                type="submit"
                                :disabled="processing"
                            >
                                <ShieldBan />
                                Disable 2FA
                            </Button>
                        </Form>
                    </div>
                </div>

                <TwoFactorSetupModal
                    v-model:isOpen="showSetupModal"
                    :requiresConfirmation="requiresConfirmation"
                    :twoFactorEnabled="twoFactorEnabled"
                />
            </div>

            <div v-if="canManagePasskeys" class="space-y-6">
                <Heading
                    variant="small"
                    title="Passkeys"
                    description="Manage your passkeys for passwordless sign-in"
                />

                <div class="overflow-hidden rounded-lg border border-border">
                    <template v-if="passkeys.length">
                        <PasskeyItem
                            v-for="passkey in passkeys"
                            :key="passkey.id"
                            :passkey="passkey"
                            @remove="handleDelete"
                        />
                    </template>

                    <div v-else class="p-8 text-center">
                        <div
                            class="mx-auto mb-4 flex h-14 w-14 items-center justify-center rounded-2xl bg-muted"
                        >
                            <KeyRound class="h-7 w-7 text-muted-foreground" />
                        </div>
                        <p class="font-medium">No passkeys yet</p>
                        <p class="mt-1 text-sm text-muted-foreground">
                            Add a passkey to sign in without a password
                        </p>
                    </div>
                </div>

                <PasskeyRegister @success="handleRegisterSuccess" />
            </div>
        </SettingsLayout>
    </AppLayout>
</template>

// kits/Inertia/Fortify/Svelte/resources/js/pages/settings/Security.svelte
<script lang="ts">
    import { Form, router } from '@inertiajs/svelte';
    import KeyRound from 'lucide-svelte/icons/key-round';
    import ShieldBan from 'lucide-svelte/icons/shield-ban';
    import ShieldCheck from 'lucide-svelte/icons/shield-check';
    import { onDestroy } from 'svelte';
    import { destroy } from '@/actions/Laravel/Passkeys/Http/Controllers/PasskeyRegistrationController';
    import SecurityController from '@/actions/App/Http/Controllers/Settings/SecurityController';
    import AppHead from '@/components/AppHead.svelte';
    import Heading from '@/components/Heading.svelte';
    import InputError from '@/components/InputError.svelte';
    import PasskeyItem from '@/components/PasskeyItem.svelte';
    import PasskeyRegister from '@/components/PasskeyRegister.svelte';
    import PasswordInput from '@/components/PasswordInput.svelte';
    import TwoFactorRecoveryCodes from '@/components/TwoFactorRecoveryCodes.svelte';
    import TwoFactorSetupModal from '@/components/TwoFactorSetupModal.svelte';
    import { Badge } from '@/components/ui/badge';
    import { Button } from '@/components/ui/button';
    import { Label } from '@/components/ui/label';
    import AppLayout from '@/layouts/AppLayout.svelte';
    import SettingsLayout from '@/layouts/settings/Layout.svelte';
    import { twoFactorAuthState } from '@/lib/twoFactorAuth.svelte';
    import { edit } from '@/routes/security';
    import { disable, enable } from '@/routes/two-factor';
    import type { BreadcrumbItem } from '@/types';

    type Passkey = {
        id: number;
        name: string;
        authenticator: string | null;
        created_at_diff: string;
        last_used_at_diff: string | null;
    };

    let {
        canManageTwoFactor = false,
        canManagePasskeys = false,
        passkeys = [],
        requiresConfirmation = false,
        twoFactorEnabled = false,
    }: {
        canManageTwoFactor?: boolean;
        canManagePasskeys?: boolean;
        passkeys?: Passkey[];
        requiresConfirmation?: boolean;
        twoFactorEnabled?: boolean;
    } = $props();

    const breadcrumbs: BreadcrumbItem[] = [
        {
            title: 'Security settings',
            href: edit(),
        },
    ];

    const twoFactorAuth = twoFactorAuthState();
    let showSetupModal = $state(false);

    function handleDelete(id: number) {
        router.delete(destroy.url(id), {
            preserveScroll: true,
        });
    }

    function handleRegisterSuccess() {
        router.reload({
            preserveScroll: true,
        });
    }

    onDestroy(() => twoFactorAuth.clearTwoFactorAuthData());
</script>

<AppHead title="Security settings" />

<AppLayout {breadcrumbs}>
    <h1 class="sr-only">Security settings</h1>

    <SettingsLayout>
        <div class="space-y-6">
            <Heading
                variant="small"
                title="Update password"
                description="Ensure your account is using a long, random password to stay secure"
            />

            <Form
                {...SecurityController.update.form()}
                class="space-y-6"
                options={{ preserveScroll: true }}
                resetOnSuccess
                resetOnError={[
                    'password',
                    'password_confirmation',
                    'current_password',
                ]}
            >
                {#snippet children({ errors, processing, recentlySuccessful })}
                    <div class="grid gap-2">
                        <Label for="current_password">Current password</Label>
                        <PasswordInput
                            id="current_password"
                            name="current_password"
                            class="mt-1 block w-full"
                            autocomplete="current-password"
                            placeholder="Current password"
                        />
                        <InputError message={errors.current_password} />
                    </div>

                    <div class="grid gap-2">
                        <Label for="password">New password</Label>
                        <PasswordInput
                            id="password"
                            name="password"
                            class="mt-1 block w-full"
                            autocomplete="new-password"
                            placeholder="New password"
                        />
                        <InputError message={errors.password} />
                    </div>

                    <div class="grid gap-2">
                        <Label for="password_confirmation"
                            >Confirm password</Label
                        >
                        <PasswordInput
                            id="password_confirmation"
                            name="password_confirmation"
                            class="mt-1 block w-full"
                            autocomplete="new-password"
                            placeholder="Confirm password"
                        />
                        <InputError message={errors.password_confirmation} />
                    </div>

                    <div class="flex items-center gap-4">
                        <Button
                            type="submit"
                            disabled={processing}
                            data-test="update-password-button"
                        >
                            Save password
                        </Button>

                        {#if recentlySuccessful}
                            <p class="text-sm text-neutral-600">Saved.</p>
                        {/if}
                    </div>
                {/snippet}
            </Form>
        </div>

        {#if canManageTwoFactor}
            <div class="space-y-6">
                <Heading
                    variant="small"
                    title="Two-factor authentication"
                    description="Manage your two-factor authentication settings"
                />

                {#if !twoFactorEnabled}
                    <div
                        class="flex flex-col items-start justify-start space-y-4"
                    >
                        <Badge variant="destructive">Disabled</Badge>

                        <p class="text-muted-foreground">
                            When you enable two-factor authentication, you will
                            be prompted for a secure pin during login. This pin
                            can be retrieved from a TOTP-supported application
                            on your phone.
                        </p>

                        <div>
                            {#if twoFactorAuth.hasSetupData()}
                                <Button onclick={() => (showSetupModal = true)}>
                                    <ShieldCheck class="size-4" />Continue setup
                                </Button>
                            {:else}
                                <Form
                                    {...enable.form()}
                                    onSuccess={() => (showSetupModal = true)}
                                >
                                    {#snippet children({ processing })}
                                        <Button
                                            type="submit"
                                            disabled={processing}
                                        >
                                            <ShieldCheck class="size-4" />Enable
                                            2FA
                                        </Button>
                                    {/snippet}
                                </Form>
                            {/if}
                        </div>
                    </div>
                {:else}
                    <div
                        class="flex flex-col items-start justify-start space-y-4"
                    >
                        <Badge variant="default">Enabled</Badge>

                        <p class="text-muted-foreground">
                            With two-factor authentication enabled, you will be
                            prompted for a secure, random pin during login,
                            which you can retrieve from the TOTP-supported
                            application on your phone.
                        </p>

                        <TwoFactorRecoveryCodes />

                        <div class="relative inline">
                            <Form {...disable.form()}>
                                {#snippet children({ processing })}
                                    <Button
                                        variant="destructive"
                                        type="submit"
                                        disabled={processing}
                                    >
                                        <ShieldBan class="size-4" />
                                        Disable 2FA
                                    </Button>
                                {/snippet}
                            </Form>
                        </div>
                    </div>
                {/if}

                <TwoFactorSetupModal
                    bind:isOpen={showSetupModal}
                    {requiresConfirmation}
                    {twoFactorEnabled}
                />
            </div>
        {/if}

        {#if canManagePasskeys}
            <div class="space-y-6">
                <Heading
                    variant="small"
                    title="Passkeys"
                    description="Manage your passkeys for passwordless sign-in"
                />

                <div class="overflow-hidden rounded-lg border border-border">
                    {#if passkeys.length > 0}
                        {#each passkeys as passkey (passkey.id)}
                            <PasskeyItem {passkey} onDelete={handleDelete} />
                        {/each}
                    {:else}
                        <div class="p-8 text-center">
                            <div
                                class="mx-auto mb-4 flex h-14 w-14 items-center justify-center rounded-2xl bg-muted"
                            >
                                <KeyRound class="h-7 w-7 text-muted-foreground" />
                            </div>
                            <p class="font-medium">No passkeys yet</p>
                            <p class="mt-1 text-sm text-muted-foreground">
                                Add a passkey to sign in without a password
                            </p>
                        </div>
                    {/if}
                </div>

                <PasskeyRegister onSuccess={handleRegisterSuccess} />
            </div>
        {/if}
    </SettingsLayout>
</AppLayout>
