// kits/Inertia/Fortify/Svelte/resources/js/pages/auth/VerifyEmail.svelte
<script lang="ts">
    import { Form } from '@inertiajs/svelte';
    import TextLink from '@/components/TextLink.svelte';
    import { Button } from '@/components/ui/button';
    import { Spinner } from '@/components/ui/spinner';
    import AuthLayout from '@/layouts/AuthLayout.svelte';
    import { logout } from '@/routes';
    import { send } from '@/routes/verification';

    let {
        status = '',
    }: {
        status?: string;
    } = $props();
</script>

<svelte:head>
    <title>Email verification</title>
</svelte:head>

<AuthLayout
    title="Verify email"
    description="Please verify your email address by clicking on the link we just emailed to you."
>
    {#if status === 'verification-link-sent'}
        <div class="mb-4 text-center text-sm font-medium text-green-600">
            A new verification link has been sent to the email address you provided during registration.
        </div>
    {/if}

    <Form {...send.form()} class="space-y-6 text-center">
        {#snippet children({ processing })}
            <Button disabled={processing} variant="secondary">
                {#if processing}<Spinner />{/if}
                Resend verification email
            </Button>

            <TextLink href={logout()} as="button" class="mx-auto block text-sm">
                Log out
            </TextLink>
        {/snippet}
    </Form>
</AuthLayout>

// kits/Inertia/Fortify/React/resources/js/pages/auth/verify-email.tsx
// Components
import { Form, Head, setLayoutProps } from '@inertiajs/react';
import TextLink from '@/components/text-link';
import { Button } from '@/components/ui/button';
import { Spinner } from '@/components/ui/spinner';
import { logout } from '@/routes';
import { send } from '@/routes/verification';

export default function VerifyEmail({ status }: { status?: string }) {
    setLayoutProps({
        title: 'Verify email',
        description:
            'Please verify your email address by clicking on the link we just emailed to you.',
    });

    return (
        <>
            <Head title="Email verification" />

            {status === 'verification-link-sent' && (
                <div className="mb-4 text-center text-sm font-medium text-green-600">
                    A new verification link has been sent to the email address
                    you provided during registration.
                </div>
            )}

            <Form {...send.form()} className="space-y-6 text-center">
                {({ processing }) => (
                    <>
                        <Button disabled={processing} variant="secondary">
                            {processing && <Spinner />}
                            Resend verification email
                        </Button>

                        <TextLink
                            href={logout()}
                            className="mx-auto block text-sm"
                        >
                            Log out
                        </TextLink>
                    </>
                )}
            </Form>
        </>
    );
}
