// kits/Inertia/Teams/Vue/resources/js/pages/teams/Edit.vue
<script setup lang="ts">
import { Form, Head, router } from '@inertiajs/vue3';
import { ChevronDown, Mail, Trash2, UserPlus, X } from 'lucide-vue-next';
import { computed, ref } from 'vue';
import Heading from '@/components/Heading.vue';
import InputError from '@/components/InputError.vue';
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import {
    Dialog,
    DialogClose,
    DialogContent,
    DialogDescription,
    DialogFooter,
    DialogHeader,
    DialogTitle,
    DialogTrigger,
} from '@/components/ui/dialog';
import {
    DropdownMenu,
    DropdownMenuContent,
    DropdownMenuItem,
    DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import {
    Select,
    SelectContent,
    SelectItem,
    SelectTrigger,
    SelectValue,
} from '@/components/ui/select';
import {
    Tooltip,
    TooltipContent,
    TooltipProvider,
    TooltipTrigger,
} from '@/components/ui/tooltip';
import { useInitials } from '@/composables/useInitials';
import AppLayout from '@/layouts/AppLayout.vue';
import SettingsLayout from '@/layouts/settings/Layout.vue';
import type {
    BreadcrumbItem,
    RoleOption,
    Team,
    TeamInvitation,
    TeamMember,
    TeamOption,
    TeamPermissions,
} from '@/types';
import { destroy, edit, index, update } from '@/routes/teams';
import {
    destroy as destroyInvitation,
    store as storeInvitation,
} from '@/routes/teams/invitations';
import {
    destroy as destroyMember,
    update as updateMember,
} from '@/routes/teams/members';

type Props = {
    team: Team;
    members: TeamMember[];
    invitations: TeamInvitation[];
    permissions: TeamPermissions;
    availableRoles: RoleOption[];
    isCurrentTeam: boolean;
    otherTeams: TeamOption[];
};

const props = defineProps<Props>();

const { getInitials } = useInitials();

const breadcrumbs = computed<BreadcrumbItem[]>(() => [
    {
        title: 'Teams',
        href: index().url,
    },
    {
        title: props.team.name,
        href: edit(props.team.slug).url,
    },
]);

const inviteDialogOpen = ref(false);
const deleteDialogOpen = ref(false);
const removeMemberDialogOpen = ref(false);
const memberToRemove = ref<TeamMember | null>(null);
const cancelInvitationDialogOpen = ref(false);
const invitationToCancel = ref<TeamInvitation | null>(null);
const inviteRole = ref('member');
const confirmationName = ref('');
const newCurrentTeamId = ref('');

const canDeleteTeam = computed(() => {
    const nameMatches = confirmationName.value === props.team.name;
    const hasNewTeamIfNeeded =
        !props.isCurrentTeam || newCurrentTeamId.value !== '';

    return nameMatches && hasNewTeamIfNeeded;
});

const resetDeleteDialog = () => {
    confirmationName.value = '';
    newCurrentTeamId.value = '';
};

const updateMemberRole = (member: TeamMember, newRole: string) => {
    router.patch(
        updateMember([props.team.slug, member.id]).url,
        {
            role: newRole,
        },
        {
            preserveScroll: true,
        },
    );
};

const confirmRemoveMember = (member: TeamMember) => {
    memberToRemove.value = member;
    removeMemberDialogOpen.value = true;
};

const removeMember = () => {
    if (memberToRemove.value) {
        router.delete(
            destroyMember([props.team.slug, memberToRemove.value.id]).url,
            {
                onSuccess: () => {
                    removeMemberDialogOpen.value = false;
                    memberToRemove.value = null;
                },
            },
        );
    }
};

const confirmCancelInvitation = (invitation: TeamInvitation) => {
    invitationToCancel.value = invitation;
    cancelInvitationDialogOpen.value = true;
};

const cancelInvitation = () => {
    if (invitationToCancel.value) {
        router.delete(
            destroyInvitation([props.team.slug, invitationToCancel.value.code])
                .url,
            {
                onSuccess: () => {
                    cancelInvitationDialogOpen.value = false;
                    invitationToCancel.value = null;
                },
            },
        );
    }
};

const deleteTeam = () => {
    router.delete(destroy(props.team.slug).url, {
        data: {
            name: confirmationName.value,
            new_current_team_id:
                newCurrentTeamId.value === ''
                    ? null
                    : Number(newCurrentTeamId.value),
        },
        onSuccess: () => {
            deleteDialogOpen.value = false;
            resetDeleteDialog();
        },
        onError: () => {
            // Keep the dialog open on validation errors
        },
    });
};
</script>

<template>
    <AppLayout :breadcrumbs="breadcrumbs">
        <Head :title="`Edit ${team.name}`" />

        <h1 class="sr-only">Edit Team: {{ team.name }}</h1>

        <SettingsLayout>
            <div class="flex flex-col space-y-10">
                <!-- Team Name Section -->
                <div v-if="permissions.canUpdateTeam" class="space-y-6">
                    <Heading
                        variant="small"
                        title="Team Settings"
                        description="Update your team name and settings"
                    />

                    <Form
                        v-bind="update.form(team.slug)"
                        class="space-y-6"
                        v-slot="{ errors, processing, recentlySuccessful }"
                    >
                        <div class="grid gap-2">
                            <Label for="name">Team Name</Label>
                            <Input
                                id="name"
                                name="name"
                                :default-value="team.name"
                                required
                            />
                            <InputError :message="errors.name" />
                        </div>

                        <div class="flex items-center gap-4">
                            <Button type="submit" :disabled="processing">
                                Save
                            </Button>

                            <Transition
                                enter-active-class="transition ease-in-out"
                                enter-from-class="opacity-0"
                                leave-active-class="transition ease-in-out"
                                leave-to-class="opacity-0"
                            >
                                <p
                                    v-show="recentlySuccessful"
                                    class="text-sm text-neutral-600"
                                >
                                    Saved.
                                </p>
                            </Transition>
                        </div>
                    </Form>
                </div>

                <div v-else class="space-y-6">
                    <Heading variant="small" title="Team Name" />
                    <p class="text-foreground">{{ team.name }}</p>
                </div>

                <!-- Members Section -->
                <div class="space-y-6">
                    <div class="flex items-center justify-between">
                        <Heading
                            variant="small"
                            title="Team Members"
                            :description="
                                permissions.canCreateInvitation
                                    ? 'Manage who has access to this team'
                                    : ''
                            "
                        />

                        <Dialog
                            v-model:open="inviteDialogOpen"
                            v-if="permissions.canCreateInvitation"
                        >
                            <DialogTrigger as-child>
                                <Button>
                                    <UserPlus class="mr-2 h-4 w-4" />
                                    Invite Member
                                </Button>
                            </DialogTrigger>
                            <DialogContent>
                                <Form
                                    v-bind="storeInvitation.form(team.slug)"
                                    class="space-y-6"
                                    v-slot="{ errors, processing }"
                                    @success="inviteDialogOpen = false"
                                >
                                    <DialogHeader>
                                        <DialogTitle
                                            >Invite a team member</DialogTitle
                                        >
                                        <DialogDescription>
                                            Send an invitation to join this
                                            team.
                                        </DialogDescription>
                                    </DialogHeader>

                                    <div class="grid gap-4">
                                        <div class="grid gap-2">
                                            <Label for="email"
                                                >Email Address</Label
                                            >
                                            <Input
                                                id="email"
                                                name="email"
                                                type="email"
                                                placeholder="colleague@example.com"
                                                required
                                            />
                                            <InputError
                                                :message="errors.email"
                                            />
                                        </div>

                                        <div class="grid gap-2">
                                            <Label for="role">Role</Label>
                                            <Select
                                                v-model="inviteRole"
                                                name="role"
                                            >
                                                <SelectTrigger class="w-full">
                                                    <SelectValue
                                                        placeholder="Select a role"
                                                    />
                                                </SelectTrigger>
                                                <SelectContent>
                                                    <SelectItem
                                                        v-for="role in availableRoles"
                                                        :key="role.value"
                                                        :value="role.value"
                                                    >
                                                        {{ role.label }}
                                                    </SelectItem>
                                                </SelectContent>
                                            </Select>
                                            <InputError
                                                :message="errors.role"
                                            />
                                        </div>
                                    </div>

                                    <DialogFooter class="gap-2">
                                        <DialogClose as-child>
                                            <Button variant="secondary">
                                                Cancel
                                            </Button>
                                        </DialogClose>

                                        <Button
                                            type="submit"
                                            :disabled="processing"
                                        >
                                            Send Invitation
                                        </Button>
                                    </DialogFooter>
                                </Form>
                            </DialogContent>
                        </Dialog>
                    </div>

                    <div class="space-y-3">
                        <div
                            v-for="member in members"
                            :key="member.id"
                            class="flex items-center justify-between rounded-lg border p-4"
                        >
                            <div class="flex items-center gap-4">
                                <Avatar class="h-10 w-10">
                                    <AvatarImage
                                        v-if="member.avatar"
                                        :src="member.avatar"
                                        :alt="member.name"
                                    />
                                    <AvatarFallback>{{
                                        getInitials(member.name)
                                    }}</AvatarFallback>
                                </Avatar>
                                <div>
                                    <div class="font-medium">
                                        {{ member.name }}
                                    </div>
                                    <div class="text-sm text-muted-foreground">
                                        {{ member.email }}
                                    </div>
                                </div>
                            </div>

                            <div class="flex items-center gap-2">
                                <DropdownMenu
                                    v-if="
                                        member.role !== 'owner' &&
                                        permissions.canUpdateMember
                                    "
                                >
                                    <DropdownMenuTrigger as-child>
                                        <Button variant="outline" size="sm">
                                            {{ member.role_label }}
                                            <ChevronDown
                                                class="ml-2 h-4 w-4 opacity-50"
                                            />
                                        </Button>
                                    </DropdownMenuTrigger>
                                    <DropdownMenuContent>
                                        <DropdownMenuItem
                                            v-for="role in availableRoles"
                                            :key="role.value"
                                            @click="
                                                updateMemberRole(
                                                    member,
                                                    role.value,
                                                )
                                            "
                                        >
                                            {{ role.label }}
                                        </DropdownMenuItem>
                                    </DropdownMenuContent>
                                </DropdownMenu>
                                <Badge v-else variant="secondary">
                                    {{ member.role_label }}
                                </Badge>

                                <TooltipProvider
                                    v-if="
                                        member.role !== 'owner' &&
                                        permissions.canRemoveMember
                                    "
                                >
                                    <Tooltip>
                                        <TooltipTrigger as-child>
                                            <Button
                                                variant="ghost"
                                                size="sm"
                                                @click="
                                                    confirmRemoveMember(member)
                                                "
                                            >
                                                <X class="h-4 w-4" />
                                            </Button>
                                        </TooltipTrigger>
                                        <TooltipContent>
                                            <p>Remove member</p>
                                        </TooltipContent>
                                    </Tooltip>
                                </TooltipProvider>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Pending Invitations Section -->
                <div v-if="invitations.length > 0" class="space-y-6">
                    <Heading
                        variant="small"
                        title="Pending Invitations"
                        description="Invitations that haven't been accepted yet"
                    />

                    <div class="space-y-3">
                        <div
                            v-for="invitation in invitations"
                            :key="invitation.code"
                            class="flex items-center justify-between rounded-lg border p-4"
                        >
                            <div class="flex items-center gap-4">
                                <div
                                    class="flex h-10 w-10 items-center justify-center rounded-full bg-muted"
                                >
                                    <Mail
                                        class="h-5 w-5 text-muted-foreground"
                                    />
                                </div>
                                <div>
                                    <div class="font-medium">
                                        {{ invitation.email }}
                                    </div>
                                    <div class="text-sm text-muted-foreground">
                                        {{ invitation.role_label }}
                                    </div>
                                </div>
                            </div>

                            <TooltipProvider
                                v-if="permissions.canCancelInvitation"
                            >
                                <Tooltip>
                                    <TooltipTrigger as-child>
                                        <Button
                                            variant="ghost"
                                            size="sm"
                                            @click="
                                                confirmCancelInvitation(
                                                    invitation,
                                                )
                                            "
                                        >
                                            <X class="h-4 w-4" />
                                        </Button>
                                    </TooltipTrigger>
                                    <TooltipContent>
                                        <p>Cancel invitation</p>
                                    </TooltipContent>
                                </Tooltip>
                            </TooltipProvider>
                        </div>
                    </div>
                </div>

                <!-- Danger Zone -->
                <div
                    v-if="permissions.canDeleteTeam && !team.is_personal"
                    class="space-y-6"
                >
                    <Heading
                        variant="small"
                        title="Danger Zone"
                        description="Irreversible and destructive actions"
                    />
                    <div
                        class="space-y-4 rounded-lg border border-red-100 bg-red-50 p-4 dark:border-red-200/10 dark:bg-red-700/10"
                    >
                        <div
                            class="relative space-y-0.5 text-red-600 dark:text-red-100"
                        >
                            <p class="font-medium">Delete this team</p>
                            <p class="text-sm">
                                Once you delete a team, there is no going back.
                                Please be certain.
                            </p>
                        </div>
                        <Dialog
                            v-model:open="deleteDialogOpen"
                            @update:open="
                                (open) => !open && resetDeleteDialog()
                            "
                        >
                            <DialogTrigger as-child>
                                <Button variant="destructive">
                                    <Trash2 class="mr-2 h-4 w-4" />
                                    Delete Team
                                </Button>
                            </DialogTrigger>
                            <DialogContent>
                                <DialogHeader>
                                    <DialogTitle>Are you sure?</DialogTitle>
                                    <DialogDescription>
                                        This action cannot be undone. This will
                                        permanently delete the team
                                        <strong>{{ team.name }}</strong> and
                                        remove all of its members.
                                    </DialogDescription>
                                </DialogHeader>

                                <div class="space-y-4 py-4">
                                    <div class="grid gap-2">
                                        <Label for="confirmation-name">
                                            Type
                                            <strong>{{ team.name }}</strong> to
                                            confirm
                                        </Label>
                                        <Input
                                            id="confirmation-name"
                                            v-model="confirmationName"
                                            placeholder="Enter team name"
                                            autocomplete="off"
                                        />
                                    </div>

                                    <div
                                        v-if="
                                            isCurrentTeam &&
                                            otherTeams.length > 0
                                        "
                                        class="grid gap-2"
                                    >
                                        <Label for="new-current-team">
                                            Select a new current team
                                        </Label>
                                        <Select v-model="newCurrentTeamId">
                                            <SelectTrigger class="w-full">
                                                <SelectValue
                                                    placeholder="Select a team"
                                                />
                                            </SelectTrigger>
                                            <SelectContent>
                                                <SelectItem
                                                    v-for="otherTeam in otherTeams"
                                                    :key="otherTeam.id"
                                                    :value="
                                                        String(otherTeam.id)
                                                    "
                                                >
                                                    {{ otherTeam.name }}
                                                    <span
                                                        v-if="
                                                            otherTeam.is_personal
                                                        "
                                                        class="ml-2 text-muted-foreground"
                                                        >(Personal)</span
                                                    >
                                                </SelectItem>
                                            </SelectContent>
                                        </Select>
                                        <p
                                            class="text-sm text-muted-foreground"
                                        >
                                            You are deleting your current team.
                                            Please select which team to switch
                                            to.
                                        </p>
                                    </div>

                                    <div
                                        v-else-if="
                                            isCurrentTeam &&
                                            otherTeams.length === 0
                                        "
                                        class="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-800 dark:border-red-200/20 dark:bg-red-900/20 dark:text-red-200"
                                    >
                                        You cannot delete your current team
                                        because you have no other teams to
                                        switch to. Please create or join another
                                        team first.
                                    </div>
                                </div>

                                <DialogFooter class="gap-2">
                                    <DialogClose as-child>
                                        <Button variant="secondary">
                                            Cancel
                                        </Button>
                                    </DialogClose>

                                    <Button
                                        variant="destructive"
                                        :disabled="!canDeleteTeam"
                                        @click="deleteTeam"
                                    >
                                        Delete Team
                                    </Button>
                                </DialogFooter>
                            </DialogContent>
                        </Dialog>
                    </div>
                </div>
            </div>

            <!-- Remove Member Confirmation Dialog -->
            <Dialog v-model:open="removeMemberDialogOpen">
                <DialogContent>
                    <DialogHeader>
                        <DialogTitle>Remove team member</DialogTitle>
                        <DialogDescription>
                            Are you sure you want to remove
                            <strong>{{ memberToRemove?.name }}</strong> from
                            this team?
                        </DialogDescription>
                    </DialogHeader>

                    <DialogFooter class="gap-2">
                        <DialogClose as-child>
                            <Button variant="secondary"> Cancel </Button>
                        </DialogClose>

                        <Button variant="destructive" @click="removeMember">
                            Remove Member
                        </Button>
                    </DialogFooter>
                </DialogContent>
            </Dialog>

            <!-- Cancel Invitation Confirmation Dialog -->
            <Dialog v-model:open="cancelInvitationDialogOpen">
                <DialogContent>
                    <DialogHeader>
                        <DialogTitle>Cancel invitation</DialogTitle>
                        <DialogDescription>
                            Are you sure you want to cancel the invitation for
                            <strong>{{ invitationToCancel?.email }}</strong
                            >?
                        </DialogDescription>
                    </DialogHeader>

                    <DialogFooter class="gap-2">
                        <DialogClose as-child>
                            <Button variant="secondary">
                                Keep Invitation
                            </Button>
                        </DialogClose>

                        <Button variant="destructive" @click="cancelInvitation">
                            Cancel Invitation
                        </Button>
                    </DialogFooter>
                </DialogContent>
            </Dialog>
        </SettingsLayout>
    </AppLayout>
</template>

// kits/Inertia/Teams/Svelte/resources/js/pages/teams/Edit.svelte
<script lang="ts">
    import { Form, router } from '@inertiajs/svelte';
    import ChevronDown from 'lucide-svelte/icons/chevron-down';
    import Mail from 'lucide-svelte/icons/mail';
    import Trash2 from 'lucide-svelte/icons/trash-2';
    import UserPlus from 'lucide-svelte/icons/user-plus';
    import X from 'lucide-svelte/icons/x';
    import AppHead from '@/components/AppHead.svelte';
    import Heading from '@/components/Heading.svelte';
    import InputError from '@/components/InputError.svelte';
    import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar';
    import { Badge } from '@/components/ui/badge';
    import { Button } from '@/components/ui/button';
    import {
        Dialog,
        DialogClose,
        DialogContent,
        DialogDescription,
        DialogFooter,
        DialogTitle,
        DialogTrigger,
    } from '@/components/ui/dialog';
    import {
        DropdownMenu,
        DropdownMenuContent,
        DropdownMenuItem,
        DropdownMenuTrigger,
    } from '@/components/ui/dropdown-menu';
    import { Input } from '@/components/ui/input';
    import { Label } from '@/components/ui/label';
    import {
        Select,
        SelectContent,
        SelectItem,
        SelectTrigger,
    } from '@/components/ui/select';
    import {
        Tooltip,
        TooltipContent,
        TooltipProvider,
        TooltipTrigger,
    } from '@/components/ui/tooltip';
    import AppLayout from '@/layouts/AppLayout.svelte';
    import SettingsLayout from '@/layouts/settings/Layout.svelte';
    import { getInitials } from '@/lib/initials';
    import { destroy, edit, index, update } from '@/routes/teams';
    import {
        destroy as destroyInvitation,
        store as storeInvitation,
    } from '@/routes/teams/invitations';
    import {
        destroy as destroyMember,
        update as updateMember,
    } from '@/routes/teams/members';
    import type {
        BreadcrumbItem,
        RoleOption,
        Team,
        TeamInvitation,
        TeamMember,
        TeamOption,
        TeamPermissions,
    } from '@/types';

    let {
        team,
        members,
        invitations,
        permissions,
        availableRoles,
        isCurrentTeam,
        otherTeams,
    }: {
        team: Team;
        members: TeamMember[];
        invitations: TeamInvitation[];
        permissions: TeamPermissions;
        availableRoles: RoleOption[];
        isCurrentTeam: boolean;
        otherTeams: TeamOption[];
    } = $props();

    const breadcrumbs = $derived<BreadcrumbItem[]>([
        {
            title: 'Teams',
            href: index().url,
        },
        {
            title: team.name,
            href: edit(team.slug).url,
        },
    ]);

    let inviteDialogOpen = $state(false);
    let deleteDialogOpen = $state(false);
    let removeMemberDialogOpen = $state(false);
    let memberToRemove = $state<TeamMember | null>(null);
    let cancelInvitationDialogOpen = $state(false);
    let invitationToCancel = $state<TeamInvitation | null>(null);
    let inviteRole = $state<RoleOption['value']>('member');
    let confirmationName = $state('');
    let newCurrentTeamId = $state('');

    const canDeleteTeam = $derived(
        confirmationName === team.name && (!isCurrentTeam || newCurrentTeamId !== ''),
    );

    const inviteRoleLabel = $derived(
        availableRoles.find((role) => role.value === inviteRole)?.label ?? 'Select a role',
    );

    const selectedNewCurrentTeam = $derived(
        otherTeams.find((otherTeam) => String(otherTeam.id) === newCurrentTeamId),
    );

    const resetDeleteDialog = () => {
        confirmationName = '';
        newCurrentTeamId = '';
    };

    const updateMemberRole = (member: TeamMember, newRole: string) => {
        router.patch(
            updateMember([team.slug, member.id]).url,
            { role: newRole },
            { preserveScroll: true },
        );
    };

    const confirmRemoveMember = (member: TeamMember) => {
        memberToRemove = member;
        removeMemberDialogOpen = true;
    };

    const removeMember = () => {
        if (!memberToRemove) {
            return;
        }

        router.delete(destroyMember([team.slug, memberToRemove.id]).url, {
            onSuccess: () => {
                removeMemberDialogOpen = false;
                memberToRemove = null;
            },
        });
    };

    const confirmCancelInvitation = (invitation: TeamInvitation) => {
        invitationToCancel = invitation;
        cancelInvitationDialogOpen = true;
    };

    const callClickHandler = (handler: unknown, event: MouseEvent) => {
        if (typeof handler === 'function') {
            handler(event);
        }
    };

    const cancelInvitation = () => {
        if (!invitationToCancel) {
            return;
        }

        router.delete(destroyInvitation([team.slug, invitationToCancel.code]).url, {
            onSuccess: () => {
                cancelInvitationDialogOpen = false;
                invitationToCancel = null;
            },
        });
    };

    const deleteTeam = () => {
        router.delete(destroy(team.slug).url, {
            data: {
                name: confirmationName,
                new_current_team_id: newCurrentTeamId === '' ? null : Number(newCurrentTeamId),
            },
            onSuccess: () => {
                deleteDialogOpen = false;
                resetDeleteDialog();
            },
        });
    };
</script>

<AppHead title={`Edit ${team.name}`} />

<AppLayout {breadcrumbs}>
    <h1 class="sr-only">Edit Team: {team.name}</h1>

    <SettingsLayout>
        <div class="flex flex-col space-y-10">
            <div class="space-y-6">
                {#if permissions.canUpdateTeam}
                    <Heading
                        variant="small"
                        title="Team Settings"
                        description="Update your team name and settings"
                    />

                    <Form {...update.form(team.slug)} class="space-y-6">
                        {#snippet children({ errors, processing, recentlySuccessful })}
                            <div class="grid gap-2">
                                <Label for="name">Team Name</Label>
                                <Input id="name" name="name" value={team.name} required />
                                <InputError message={errors.name} />
                            </div>

                            <div class="flex items-center gap-4">
                                <Button type="submit" disabled={processing}>Save</Button>

                                {#if recentlySuccessful}
                                    <p class="text-sm text-neutral-600">Saved.</p>
                                {/if}
                            </div>
                        {/snippet}
                    </Form>
                {:else}
                    <Heading variant="small" title="Team Name" />
                    <p class="text-foreground">{team.name}</p>
                {/if}
            </div>

            <div class="space-y-6">
                <div class="flex items-center justify-between">
                    <Heading
                        variant="small"
                        title="Team Members"
                        description={permissions.canCreateInvitation
                            ? 'Manage who has access to this team'
                            : ''}
                    />

                    {#if permissions.canCreateInvitation}
                        <Dialog bind:open={inviteDialogOpen}>
                            <DialogTrigger asChild>
                                {#snippet children(props)}
                                    <Button onclick={(event) => callClickHandler(props.onClick, event)}>
                                        <UserPlus class="mr-2 h-4 w-4" />
                                        Invite Member
                                    </Button>
                                {/snippet}
                            </DialogTrigger>
                            <DialogContent>
                                <Form
                                    {...storeInvitation.form(team.slug)}
                                    class="space-y-6"
                                    onSuccess={() => (inviteDialogOpen = false)}
                                >
                                    {#snippet children({ errors, processing })}
                                        <div class="space-y-3">
                                            <DialogTitle>Invite a team member</DialogTitle>
                                            <DialogDescription>
                                                Send an invitation to join this team.
                                            </DialogDescription>
                                        </div>

                                        <div class="grid gap-4">
                                            <div class="grid gap-2">
                                                <Label for="email">Email Address</Label>
                                                <Input
                                                    id="email"
                                                    name="email"
                                                    type="email"
                                                    placeholder="colleague@example.com"
                                                    required
                                                />
                                                <InputError message={errors.email} />
                                            </div>

                                            <div class="grid gap-2">
                                                <Label for="role">Role</Label>
                                                <Select bind:value={inviteRole}>
                                                    <SelectTrigger class="w-full">
                                                        {inviteRoleLabel}
                                                    </SelectTrigger>
                                                    <SelectContent>
                                                        {#each availableRoles as role (role.value)}
                                                            <SelectItem value={role.value} label={role.label}>
                                                                {role.label}
                                                            </SelectItem>
                                                        {/each}
                                                    </SelectContent>
                                                </Select>

                                                <input type="hidden" name="role" value={inviteRole} />
                                                <InputError message={errors.role} />
                                            </div>
                                        </div>

                                        <DialogFooter class="gap-2">
                                            <DialogClose>
                                                <Button variant="secondary">Cancel</Button>
                                            </DialogClose>

                                            <Button type="submit" disabled={processing}>Send Invitation</Button>
                                        </DialogFooter>
                                    {/snippet}
                                </Form>
                            </DialogContent>
                        </Dialog>
                    {/if}
                </div>

                <div class="space-y-3">
                    {#each members as member (member.id)}
                        <div class="flex items-center justify-between rounded-lg border p-4">
                            <div class="flex items-center gap-4">
                                <Avatar class="h-10 w-10">
                                    {#if member.avatar}
                                        <AvatarImage src={member.avatar} alt={member.name} />
                                    {/if}
                                    <AvatarFallback>{getInitials(member.name)}</AvatarFallback>
                                </Avatar>

                                <div>
                                    <div class="font-medium">{member.name}</div>
                                    <div class="text-sm text-muted-foreground">{member.email}</div>
                                </div>
                            </div>

                            <div class="flex items-center gap-2">
                                {#if member.role !== 'owner' && permissions.canUpdateMember}
                                    <DropdownMenu>
                                        <DropdownMenuTrigger asChild>
                                            {#snippet children(props)}
                                                <Button
                                                    variant="outline"
                                                    size="sm"
                                                    onclick={props.onclick}
                                                    aria-expanded={props['aria-expanded']}
                                                    data-state={props['data-state']}
                                                >
                                                    {member.role_label}
                                                    <ChevronDown class="ml-2 h-4 w-4 opacity-50" />
                                                </Button>
                                            {/snippet}
                                        </DropdownMenuTrigger>
                                        <DropdownMenuContent>
                                            {#each availableRoles as role (role.value)}
                                                <DropdownMenuItem asChild>
                                                    {#snippet children(props)}
                                                        <button
                                                            type="button"
                                                            class={props.class}
                                                            onclick={(event) => {
                                                                props.onClick?.(event);
                                                                updateMemberRole(member, role.value);
                                                            }}
                                                        >
                                                            {role.label}
                                                        </button>
                                                    {/snippet}
                                                </DropdownMenuItem>
                                            {/each}
                                        </DropdownMenuContent>
                                    </DropdownMenu>
                                {:else}
                                    <Badge variant="secondary">{member.role_label}</Badge>
                                {/if}

                                {#if member.role !== 'owner' && permissions.canRemoveMember}
                                    <TooltipProvider delayDuration={0}>
                                        <Tooltip>
                                            <TooltipTrigger>
                                                {#snippet child({ props })}
                                                    <Button
                                                        variant="ghost"
                                                        size="sm"
                                                        {...props}
                                                        onclick={(event) => {
                                                            callClickHandler(props.onClick, event);
                                                            confirmRemoveMember(member);
                                                        }}
                                                    >
                                                        <X class="h-4 w-4" />
                                                    </Button>
                                                {/snippet}
                                            </TooltipTrigger>
                                            <TooltipContent>
                                                <p>Remove member</p>
                                            </TooltipContent>
                                        </Tooltip>
                                    </TooltipProvider>
                                {/if}
                            </div>
                        </div>
                    {/each}
                </div>
            </div>

            {#if invitations.length > 0}
                <div class="space-y-6">
                    <Heading
                        variant="small"
                        title="Pending Invitations"
                        description="Invitations that haven't been accepted yet"
                    />

                    <div class="space-y-3">
                        {#each invitations as invitation (invitation.code)}
                            <div class="flex items-center justify-between rounded-lg border p-4">
                                <div class="flex items-center gap-4">
                                    <div class="flex h-10 w-10 items-center justify-center rounded-full bg-muted">
                                        <Mail class="h-5 w-5 text-muted-foreground" />
                                    </div>
                                    <div>
                                        <div class="font-medium">{invitation.email}</div>
                                        <div class="text-sm text-muted-foreground">{invitation.role_label}</div>
                                    </div>
                                </div>

                                {#if permissions.canCancelInvitation}
                                    <TooltipProvider delayDuration={0}>
                                        <Tooltip>
                                            <TooltipTrigger>
                                                {#snippet child({ props })}
                                                    <Button
                                                        variant="ghost"
                                                        size="sm"
                                                        {...props}
                                                        onclick={(event) => {
                                                            callClickHandler(props.onClick, event);
                                                            confirmCancelInvitation(invitation);
                                                        }}
                                                    >
                                                        <X class="h-4 w-4" />
                                                    </Button>
                                                {/snippet}
                                            </TooltipTrigger>
                                            <TooltipContent>
                                                <p>Cancel invitation</p>
                                            </TooltipContent>
                                        </Tooltip>
                                    </TooltipProvider>
                                {/if}
                            </div>
                        {/each}
                    </div>
                </div>
            {/if}

            {#if permissions.canDeleteTeam && !team.is_personal}
                <div class="space-y-6">
                    <Heading
                        variant="small"
                        title="Danger Zone"
                        description="Irreversible and destructive actions"
                    />
                    <div class="space-y-4 rounded-lg border border-red-100 bg-red-50 p-4 dark:border-red-200/10 dark:bg-red-700/10">
                        <div class="relative space-y-0.5 text-red-600 dark:text-red-100">
                            <p class="font-medium">Delete this team</p>
                            <p class="text-sm">Once you delete a team, there is no going back. Please be certain.</p>
                        </div>

                        <Dialog bind:open={deleteDialogOpen}>
                            <DialogTrigger asChild>
                                {#snippet children(props)}
                                    <Button
                                        variant="destructive"
                                        onclick={(event) => callClickHandler(props.onClick, event)}
                                    >
                                        <Trash2 class="mr-2 h-4 w-4" />
                                        Delete Team
                                    </Button>
                                {/snippet}
                            </DialogTrigger>

                            <DialogContent>
                                <div class="space-y-3">
                                    <DialogTitle>Are you sure?</DialogTitle>
                                    <DialogDescription>
                                        This action cannot be undone. This will permanently delete the team
                                        <strong>{team.name}</strong> and remove all of its members.
                                    </DialogDescription>
                                </div>

                                <div class="space-y-4 py-4">
                                    <div class="grid gap-2">
                                        <Label for="confirmation-name">
                                            Type <strong>{team.name}</strong> to confirm
                                        </Label>
                                        <Input
                                            id="confirmation-name"
                                            value={confirmationName}
                                            oninput={(event) =>
                                                (confirmationName = (event.currentTarget as HTMLInputElement).value)}
                                            placeholder="Enter team name"
                                            autocomplete="off"
                                        />
                                    </div>

                                    {#if isCurrentTeam && otherTeams.length > 0}
                                        <div class="grid gap-2">
                                            <Label for="new-current-team">Select a new current team</Label>

                                            <Select bind:value={newCurrentTeamId}>
                                                <SelectTrigger class="w-full">
                                                    {selectedNewCurrentTeam?.name ?? 'Select a team'}
                                                </SelectTrigger>
                                                <SelectContent>
                                                    {#each otherTeams as otherTeam (otherTeam.id)}
                                                        <SelectItem
                                                            value={String(otherTeam.id)}
                                                            label={otherTeam.name}
                                                        >
                                                            {otherTeam.name}
                                                            {#if otherTeam.is_personal}
                                                                <span class="ml-2 text-muted-foreground">(Personal)</span>
                                                            {/if}
                                                        </SelectItem>
                                                    {/each}
                                                </SelectContent>
                                            </Select>

                                            <p class="text-sm text-muted-foreground">
                                                You are deleting your current team. Please select which team to switch to.
                                            </p>
                                        </div>
                                    {:else if isCurrentTeam && otherTeams.length === 0}
                                        <div class="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-800 dark:border-red-200/20 dark:bg-red-900/20 dark:text-red-200">
                                            You cannot delete your current team because you have no other teams to switch to. Please create or join another team first.
                                        </div>
                                    {/if}
                                </div>

                                <DialogFooter class="gap-2">
                                    <DialogClose>
                                        <Button variant="secondary" onclick={resetDeleteDialog}>Cancel</Button>
                                    </DialogClose>

                                    <Button variant="destructive" disabled={!canDeleteTeam} onclick={deleteTeam}>
                                        Delete Team
                                    </Button>
                                </DialogFooter>
                            </DialogContent>
                        </Dialog>
                    </div>
                </div>
            {/if}
        </div>

        <Dialog bind:open={removeMemberDialogOpen}>
            <DialogContent>
                <div class="space-y-3">
                    <DialogTitle>Remove team member</DialogTitle>
                    <DialogDescription>
                        Are you sure you want to remove <strong>{memberToRemove?.name}</strong> from this team?
                    </DialogDescription>
                </div>

                <DialogFooter class="gap-2">
                    <DialogClose>
                        <Button variant="secondary">Cancel</Button>
                    </DialogClose>

                    <Button variant="destructive" onclick={removeMember}>Remove Member</Button>
                </DialogFooter>
            </DialogContent>
        </Dialog>

        <Dialog bind:open={cancelInvitationDialogOpen}>
            <DialogContent>
                <div class="space-y-3">
                    <DialogTitle>Cancel invitation</DialogTitle>
                    <DialogDescription class="mb-3">
                        Are you sure you want to cancel the invitation for <strong>{invitationToCancel?.email}</strong>?
                    </DialogDescription>
                </div>

                <DialogFooter class="gap-2">
                    <DialogClose>
                        <Button variant="secondary">Keep Invitation</Button>
                    </DialogClose>

                    <Button variant="destructive" onclick={cancelInvitation}>Cancel Invitation</Button>
                </DialogFooter>
            </DialogContent>
        </Dialog>
    </SettingsLayout>
</AppLayout>
