// kits/Inertia/Fortify/Svelte/resources/js/layouts/AuthLayout.svelte
<script lang="ts">
    import { useLayoutProps } from '@inertiajs/svelte';
    import type { Snippet } from 'svelte';
    import AuthLayout from '@/layouts/auth/AuthSimpleLayout.svelte';

    let {
        children,
    }: {
        children?: Snippet;
    } = $props();

    const layout = useLayoutProps({
        title: '',
        description: '',
    });
</script>

<AuthLayout title={layout.title} description={layout.description}>
    {@render children?.()}
</AuthLayout>

// kits/Inertia/Fortify/Vue/resources/js/layouts/AuthLayout.vue
<script setup lang="ts">
import { useLayoutProps } from '@inertiajs/vue3';
import AuthLayout from '@/layouts/auth/AuthSimpleLayout.vue';

const layout = useLayoutProps({
    title: '',
    description: '',
});
</script>

<template>
    <AuthLayout :title="layout.title" :description="layout.description">
        <slot />
    </AuthLayout>
</template>
