// kits/Inertia/React/resources/js/pages/settings/appearance.tsx
import { Head, setLayoutProps } from '@inertiajs/react';
import AppearanceTabs from '@/components/appearance-tabs';
import Heading from '@/components/heading';
import { edit as editAppearance } from '@/routes/appearance';

export default function Appearance() {
    setLayoutProps({
        breadcrumbs: [
            {
                title: 'Appearance settings',
                href: editAppearance(),
            },
        ],
    });

    return (
        <>
            <Head title="Appearance settings" />

            <h1 className="sr-only">Appearance settings</h1>

            <div className="space-y-6">
                <Heading
                    variant="small"
                    title="Appearance settings"
                    description="Update your account's appearance settings"
                />
                <AppearanceTabs />
            </div>
        </>
    );
}

// kits/Inertia/Svelte/resources/js/pages/settings/Appearance.svelte
<script lang="ts">
    import { setLayoutProps } from '@inertiajs/svelte';
    import AppearanceTabs from '@/components/AppearanceTabs.svelte';
    import AppHead from '@/components/AppHead.svelte';
    import Heading from '@/components/Heading.svelte';
    import { edit as editAppearance } from '@/routes/appearance';

    setLayoutProps({
        breadcrumbs: [{ title: 'Appearance settings', href: editAppearance() }],
    });
</script>

<AppHead title="Appearance settings" />

<h1 class="sr-only">Appearance settings</h1>

<div class="space-y-6">
    <Heading
        variant="small"
        title="Appearance settings"
        description="Update your account's appearance settings"
    />
    <AppearanceTabs />
</div>
