// kits/Inertia/React/resources/js/components/input-error.tsx
import type { HTMLAttributes } from 'react';
import { cn } from '@/lib/utils';

export default function InputError({
    message,
    className = '',
    ...props
}: HTMLAttributes<HTMLParagraphElement> & { message?: string | string[] }) {
    const messages = Array.isArray(message) ? message : message ? [message] : [];

    return messages.length ? (
        <p
            {...props}
            className={cn('text-sm text-red-600 dark:text-red-400', className)}
        >
            {messages.map((message, index) => (
                <span key={index} className="block">
                    {message}
                </span>
            ))}
        </p>
    ) : null;
}

// kits/Inertia/Vue/resources/js/components/InputError.vue
<script setup lang="ts">
defineProps<{
    message?: string | string[];
}>();
</script>

<template>
    <div v-show="message?.length">
        <p
            v-for="(msg, index) in Array.isArray(message) ? message : [message]"
            :key="index"
            v-show="msg"
            class="text-sm text-red-600 dark:text-red-500"
        >
            {{ msg }}
        </p>
    </div>
</template>
