// kits/Inertia/Svelte/resources/js/layouts/AppLayout.svelte
<script lang="ts">
    import { useLayoutProps } from '@inertiajs/svelte';
    import type { Snippet } from 'svelte';
    import AppLayout from '@/layouts/app/AppSidebarLayout.svelte';
    import type { BreadcrumbItem } from '@/types';

    let {
        children,
    }: {
        children?: Snippet;
    } = $props();

    const layout = useLayoutProps({
        breadcrumbs: [] as BreadcrumbItem[],
    });
</script>

<AppLayout breadcrumbs={layout.breadcrumbs}>
    {@render children?.()}
</AppLayout>

// kits/Inertia/React/resources/js/layouts/app-layout.tsx
import { useLayoutProps } from '@inertiajs/react';
import AppLayoutTemplate from '@/layouts/app/app-sidebar-layout';
import type { BreadcrumbItem } from '@/types';

export default function AppLayout({ children }: { children: React.ReactNode }) {
    const { breadcrumbs } = useLayoutProps({
        breadcrumbs: [] as BreadcrumbItem[],
    });

    return (
        <AppLayoutTemplate breadcrumbs={breadcrumbs}>
            {children}
        </AppLayoutTemplate>
    );
}
