// kits/Inertia/Vue/resources/js/components/InputError.vue
<script setup lang="ts">
defineProps<{
    message?: string | string[];
}>();
</script>

<template>
    <div v-show="message?.length">
        <p
            v-for="(msg, index) in Array.isArray(message) ? message : [message]"
            :key="index"
            v-show="msg"
            class="text-sm text-red-600 dark:text-red-500"
        >
            {{ msg }}
        </p>
    </div>
</template>

// kits/Inertia/Svelte/resources/js/components/InputError.svelte
<script lang="ts">
    let {
        message = '',
        class: className = '',
    }: {
        message?: string | string[];
        class?: string;
    } = $props();
</script>

{#if Array.isArray(message) ? message.length : message}
    <div class={className}>
        {#each Array.isArray(message) ? message : [message] as msg (msg)}
            {#if msg}
                <p class="text-sm text-red-600 dark:text-red-500">{msg}</p>
            {/if}
        {/each}
    </div>
{/if}
