// kits/Inertia/Vue/resources/js/layouts/AppLayout.vue
<script setup lang="ts">
import { useLayoutProps } from '@inertiajs/vue3';
import AppLayout from '@/layouts/app/AppSidebarLayout.vue';
import type { BreadcrumbItem } from '@/types';

const layout = useLayoutProps({
    breadcrumbs: [] as BreadcrumbItem[],
});
</script>

<template>
    <AppLayout :breadcrumbs="layout.breadcrumbs">
        <slot />
    </AppLayout>
</template>

// kits/Inertia/Svelte/resources/js/layouts/AppLayout.svelte
<script lang="ts">
    import { useLayoutProps } from '@inertiajs/svelte';
    import type { Snippet } from 'svelte';
    import AppLayout from '@/layouts/app/AppSidebarLayout.svelte';
    import type { BreadcrumbItem } from '@/types';

    let {
        children,
    }: {
        children?: Snippet;
    } = $props();

    const layout = useLayoutProps({
        breadcrumbs: [] as BreadcrumbItem[],
    });
</script>

<AppLayout breadcrumbs={layout.breadcrumbs}>
    {@render children?.()}
</AppLayout>
